blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Idea
    url: https://github.com/lvandernoll/pokecardmaker.net/discussions/new?category=ideas
    about: Have a feature request or an idea? Make a post!
  - name: â” Question
    url: https://github.com/lvandernoll/pokecardmaker.net/discussions/new?category=q-a
    about: Have a question? Ask away!
